import React from 'react';

const Charts = () => {
    return (   <>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rutrum massa nec tortor finibus lacinia. Integer lorem dolor, bibendum rutrum magna in, mollis pretium ante. Sed et lorem auctor, rutrum neque eget, semper eros. Aenean malesuada, odio id tempor condimentum, eros augue ultricies elit, ac feugiat ligula nisl auctor est. Integer aliquet tincidunt sem, eget sollicitudin felis molestie quis. Vivamus pretium turpis neque, at consectetur nibh efficitur in. Integer leo diam, vehicula quis mauris ut, fringilla egestas ante. Sed sodales ac orci sodales sollicitudin. Fusce sagittis cursus diam ut semper. Sed ultricies venenatis diam, at lacinia nulla sollicitudin id. In mattis diam justo, id efficitur leo semper non.

Quisque porta ac magna sed feugiat. Nulla a pulvinar lectus, nec facilisis arcu. Vestibulum ac ligula lectus. Curabitur ipsum velit, elementum et nunc bibendum, tincidunt congue lacus. Vestibulum malesuada erat justo, et tempus sem faucibus non. Praesent varius eros nec mauris auctor tristique. Nulla vel tincidunt nunc.

Suspendisse suscipit lacus odio, at tempus justo sollicitudin a. Aenean a viverra arcu. Nam elit lectus, ultrices sit amet purus a, scelerisque aliquam lacus. Nullam scelerisque dapibus pharetra. Phasellus tincidunt elit eu erat lobortis, nec consequat sem sollicitudin. Ut egestas auctor odio sed tempor. Suspendisse id lorem velit. Praesent et rhoncus leo. Sed a viverra sapien. Nulla facilisi. Suspendisse dictum velit diam. Nulla dapibus eleifend enim, cursus sagittis arcu sodales sed. Vestibulum sit amet imperdiet arcu.

Sed nisi orci, auctor ac tincidunt molestie, vulputate nec odio. Sed tempus dui et metus pharetra, non imperdiet sapien fringilla. Etiam ac rutrum ante. Maecenas imperdiet aliquet vehicula. Quisque sed sem iaculis, fermentum lectus ac, aliquet est. Integer lacus libero, luctus non efficitur at, ornare vel ex. Quisque a elit eget justo ultricies malesuada. Maecenas id lectus dignissim, sodales metus varius, pellentesque erat. Donec finibus nisi vitae libero tincidunt iaculis. Nunc sodales et quam vel congue. Fusce vel condimentum enim.

Curabitur accumsan quam id purus ultrices congue. Ut iaculis libero ex, sed pharetra eros aliquet ac. Vivamus et enim cursus ante tempor rutrum. Vestibulum tempor quam eget nisi rhoncus suscipit. Nam semper hendrerit augue, ac tempor sem posuere at. Nulla facilisi. In et eleifend risus. Nullam commodo ante eget erat maximus, ac dapibus ex porttitor. Aliquam rutrum hendrerit gravida. Mauris vestibulum libero non gravida eleifend.

Nullam finibus quam sed sem pulvinar, et rutrum lorem scelerisque. Sed id auctor neque. Nulla lacinia eros sit amet diam tincidunt, at lacinia nulla mattis. Morbi malesuada elit in facilisis pretium. Phasellus sit amet pharetra augue, sit amet bibendum diam. Suspendisse a nulla sit amet tortor congue porttitor a ac metus. Fusce velit elit, cursus nec rhoncus eget, mollis sit amet ante. Integer quis est sem. Fusce rutrum orci urna.

Nullam ornare lectus in semper varius. Nunc vestibulum vulputate massa ut scelerisque. Fusce nec diam condimentum elit venenatis euismod id at orci. Proin quis ipsum accumsan, ultrices elit sed, mollis turpis. Aliquam sit amet velit sit amet est feugiat tristique eget quis libero. Etiam ut arcu quam. Nam nisi tellus, volutpat vel nunc eget, semper placerat purus. Nullam cursus lacus id massa luctus, sed finibus sem feugiat. Mauris bibendum vulputate molestie.

Morbi hendrerit ut massa ac tristique. Nulla facilisi. Sed rutrum interdum ultrices. Nulla facilisi. Donec id sapien convallis, congue ipsum id, sodales metus. Vivamus vitae nibh nec turpis pharetra dignissim. Aliquam et orci nec lectus pretium viverra. Vestibulum semper hendrerit pellentesque. Vivamus nec feugiat leo. Donec sit amet lorem et orci ornare facilisis.

Fusce enim lectus, sodales ut euismod ut, elementum a sem. Nunc maximus ligula ante, non mattis diam scelerisque a. In et molestie nisi, ac viverra purus. Praesent commodo sem sapien, ac posuere nunc molestie a. Nullam aliquam, lacus in rhoncus tristique, erat diam blandit ligula, sit amet facilisis orci erat sit amet turpis. Duis convallis varius pretium. In aliquet, arcu at vehicula eleifend, nisi nibh pretium libero, at tincidunt elit lacus ut augue. Cras bibendum tempus malesuada. Aliquam hendrerit libero vel neque pellentesque sollicitudin. Praesent cursus, massa sed egestas ultricies, leo dui viverra nisl, vel aliquet risus ante at sapien. Suspendisse erat diam, tincidunt vel commodo at, porttitor accumsan libero.

Suspendisse potenti. Nullam auctor eros sapien, at egestas nibh pretium et. Nulla a euismod libero. Cras consectetur, nibh vitae condimentum interdum, est nunc cursus lectus, non dapibus lorem velit vel metus. Sed eget ex posuere, euismod diam vel, porttitor magna. Proin sem erat, malesuada placerat orci id, vehicula mattis odio. Nulla tristique orci vitae velit accumsan, nec venenatis metus molestie. Pellentesque cursus ipsum erat, eu bibendum ligula venenatis id. Phasellus consequat odio metus, eu maximus nunc faucibus sit amet. In ultricies ligula eget sollicitudin finibus. Aliquam a dolor sit amet libero consequat commodo. Nunc nec velit porta, tincidunt ipsum id, fringilla ex. Donec euismod elementum sapien, in accumsan neque tristique porttitor. Morbi vel orci ut nisi condimentum condimentum sed a odio.

Sed bibendum, diam in porta viverra, mauris lorem luctus metus, sit amet hendrerit ante libero vitae felis. Donec mi orci, pretium vel rutrum ac, dignissim in ipsum. Aliquam erat volutpat. Ut ultrices felis dui, sed commodo ipsum lacinia fermentum. Aenean ac nisi eu felis imperdiet porta. Etiam euismod eros id dapibus ultricies. In vel sapien diam. In tincidunt orci blandit, varius mauris in, porta dui. Quisque imperdiet ex eu ante suscipit, scelerisque accumsan metus dictum. Etiam finibus, augue fermentum facilisis gravida, tellus risus maximus odio, ac interdum eros mi eu justo. Donec venenatis ac magna eu ornare. Integer scelerisque sapien eu lorem eleifend laoreet.

Morbi ullamcorper tortor eget sapien consequat, ut commodo risus dignissim. Nulla semper sagittis velit sed facilisis. Vivamus vehicula, massa sit amet maximus molestie, eros risus luctus metus, quis eleifend nulla neque rhoncus justo. Fusce egestas sem a tellus pulvinar interdum. Proin varius euismod est quis tincidunt. Sed eget sapien porttitor risus consectetur laoreet at et sem. Praesent mattis tortor quis urna gravida, a malesuada lectus ultrices.

Mauris id tempus odio. Curabitur et mauris sed mauris congue tempus. Ut blandit, urna non tincidunt venenatis, justo felis luctus risus, vitae volutpat sapien ex at libero. Maecenas lobortis ornare orci, sit amet vestibulum urna vestibulum non. Quisque scelerisque placerat dignissim. Aenean accumsan diam quis nibh ultricies pellentesque. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed molestie tempus sem, vel tincidunt tellus posuere vitae. In lacinia facilisis lacus, sed suscipit leo pharetra sed. Pellentesque fermentum ullamcorper sem. Suspendisse semper fringilla nunc. Pellentesque euismod tempus nunc vel venenatis. Vestibulum tellus dolor, gravida vitae mattis sed, cursus id quam. Mauris pulvinar a urna vitae sodales.

Curabitur at arcu iaculis, lacinia dui non, gravida ex. Sed imperdiet semper vulputate. Pellentesque mattis neque a sem interdum interdum. Donec molestie consectetur convallis. Ut ut orci ac leo condimentum maximus in a augue. Nam vel tellus vitae nisl hendrerit dignissim eget sit amet purus. Praesent congue quam nec sem auctor pellentesque. Cras velit dolor, rhoncus et elit in, varius sagittis risus.

Ut ullamcorper eget est a sagittis. Phasellus vitae elementum urna. Proin lobortis, lorem non commodo finibus, nisi nibh auctor eros, quis sodales mauris elit eget velit. Nam et enim sed elit tempus egestas id ac purus. Quisque sit amet placerat velit. Aliquam vitae fringilla purus, ullamcorper pharetra tortor. Phasellus egestas maximus faucibus. Morbi porta sagittis sem nec volutpat. Suspendisse id vulputate ex. Cras eu porttitor dui.

Nunc ac eros id libero auctor sollicitudin eget eu ipsum. Vivamus scelerisque diam id aliquam suscipit. Curabitur id varius libero, eu ultrices nisl. Sed pretium mi nec neque venenatis, tempus sodales neque blandit. Vestibulum fringilla nulla eu rhoncus fermentum. Curabitur sapien sem, efficitur sagittis consequat ac, pulvinar vitae libero. Nullam convallis feugiat ante, vel commodo felis pretium id.

Aliquam efficitur, lorem rutrum lacinia vestibulum, nulla sem auctor augue, nec dictum mauris libero sed urna. Donec et lectus odio. Quisque venenatis ut libero eget commodo. Nullam ultricies fermentum finibus. Nulla semper ipsum non dui bibendum, a condimentum quam mollis. Aenean viverra diam id elit pulvinar tristique. Vestibulum eleifend ut leo ac placerat.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed suscipit ornare arcu, sit amet ullamcorper libero accumsan eu. Nunc massa urna, ornare id purus nec, sodales vulputate dui. Vestibulum feugiat dignissim dui, at tincidunt lorem luctus non. Morbi venenatis mauris nisl, sed suscipit ligula varius eget. Vivamus at elit mauris. Aenean rutrum sem nec tincidunt iaculis. Fusce condimentum malesuada nunc vel convallis. Suspendisse potenti.

Curabitur rutrum risus in scelerisque luctus. Aliquam vel arcu porttitor ante sollicitudin fringilla vitae quis quam. Vestibulum scelerisque pulvinar purus, at venenatis ipsum iaculis in. Aenean vel mollis purus, vitae tristique nulla. Quisque hendrerit orci vel orci condimentum, eu lacinia nunc accumsan. Morbi in ultricies diam. Integer orci sapien, tristique in lacinia eget, finibus ut nibh. Donec sed malesuada erat. Donec ut odio eu felis sollicitudin vulputate posuere eget lacus. Vestibulum sit amet felis congue, aliquam felis ac, cursus nibh. Pellentesque blandit dapibus faucibus. Donec nisi enim, faucibus tristique viverra eget, ultricies blandit erat. Duis vitae purus a dolor porttitor lobortis quis ut eros. Fusce rhoncus et nulla et faucibus. Aliquam accumsan fringilla nisl, ac sollicitudin tortor mattis vel.

Aenean a feugiat magna. Etiam molestie sit amet turpis id dictum. Proin metus felis, pharetra vitae sapien nec, sollicitudin bibendum lacus. Ut et elementum dui. Ut vitae scelerisque ex, non tempor felis. Vivamus consectetur posuere vestibulum. Praesent vehicula id lectus eu tempor. Aliquam vehicula, arcu at vehicula hendrerit, lectus massa rutrum libero, quis facilisis purus urna et velit. Nulla facilisi.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rutrum massa nec tortor finibus lacinia. Integer lorem dolor, bibendum rutrum magna in, mollis pretium ante. Sed et lorem auctor, rutrum neque eget, semper eros. Aenean malesuada, odio id tempor condimentum, eros augue ultricies elit, ac feugiat ligula nisl auctor est. Integer aliquet tincidunt sem, eget sollicitudin felis molestie quis. Vivamus pretium turpis neque, at consectetur nibh efficitur in. Integer leo diam, vehicula quis mauris ut, fringilla egestas ante. Sed sodales ac orci sodales sollicitudin. Fusce sagittis cursus diam ut semper. Sed ultricies venenatis diam, at lacinia nulla sollicitudin id. In mattis diam justo, id efficitur leo semper non.

Quisque porta ac magna sed feugiat. Nulla a pulvinar lectus, nec facilisis arcu. Vestibulum ac ligula lectus. Curabitur ipsum velit, elementum et nunc bibendum, tincidunt congue lacus. Vestibulum malesuada erat justo, et tempus sem faucibus non. Praesent varius eros nec mauris auctor tristique. Nulla vel tincidunt nunc.

Suspendisse suscipit lacus odio, at tempus justo sollicitudin a. Aenean a viverra arcu. Nam elit lectus, ultrices sit amet purus a, scelerisque aliquam lacus. Nullam scelerisque dapibus pharetra. Phasellus tincidunt elit eu erat lobortis, nec consequat sem sollicitudin. Ut egestas auctor odio sed tempor. Suspendisse id lorem velit. Praesent et rhoncus leo. Sed a viverra sapien. Nulla facilisi. Suspendisse dictum velit diam. Nulla dapibus eleifend enim, cursus sagittis arcu sodales sed. Vestibulum sit amet imperdiet arcu.

Sed nisi orci, auctor ac tincidunt molestie, vulputate nec odio. Sed tempus duiLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rutrum massa nec tortor finibus lacinia. Integer lorem dolor, bibendum rutrum magna in, mollis pretium ante. Sed et lorem auctor, rutrum neque eget, semper eros. Aenean malesuada, odio id tempor condimentum, eros augue ultricies elit, ac feugiat ligula nisl auctor est. Integer aliquet tincidunt sem, eget sollicitudin felis molestie quis. Vivamus pretium turpis neque, at consectetur nibh efficitur in. Integer leo diam, vehicula quis mauris ut, fringilla egestas ante. Sed sodales ac orci sodales sollicitudin. Fusce sagittis cursus diam ut semper. Sed ultricies venenatis diam, at lacinia nulla sollicitudin id. In mattis diam justo, id efficitur leo semper non.

Quisque porta ac magna sed feugiat. Nulla a pulvinar lectus, nec facilisis arcu. Vestibulum ac ligula lectus. Curabitur ipsum velit, elementum et nunc bibendum, tincidunt congue lacus. Vestibulum malesuada erat justo, et tempus sem faucibus non. Praesent varius eros nec mauris auctor tristique. Nulla vel tincidunt nunc.

Suspendisse suscipit lacus odio, at tempus justo sollicitudin a. Aenean a viverra arcu. Nam elit lectus, ultrices sit amet purus a, scelerisque aliquam lacus. Nullam scelerisque dapibus pharetra. Phasellus tincidunt elit eu erat lobortis, nec consequat sem sollicitudin. Ut egestas auctor odio sed tempor. Suspendisse id lorem velit. Praesent et rhoncus leo. Sed a viverra sapien. Nulla facilisi. Suspendisse dictum velit diam. Nulla dapibus eleifend enim, cursus sagittis arcu sodales sed. Vestibulum sit amet imperdiet arcu.

Sed nisi orci, auctor ac tincidunt molestie, vulputate nec odio. Sed tempus dui et metus pharetra, non imperdiet sapien fringilla. Etiam ac rutrum ante. Maecenas imperdiet aliquet vehicula. Quisque sed sem iaculis, fermentum lectus ac, aliquet est. Integer lacus libero, luctus non efficitur at, ornare vel ex. Quisque a elit eget justo ultricies malesuada. Maecenas id lectus dignissim, sodales metus varius, pellentesque erat. Donec finibus nisi vitae libero tincidunt iaculis. Nunc sodales et quam vel congue. Fusce vel condimentum enim.

Curabitur accumsan quam id purus ultrices congue. Ut iaculis libero ex, sed pharetra eros aliquet ac. Vivamus et enim cursus ante tempor rutrum. Vestibulum tempor quam eget nisi rhoncus suscipit. Nam semper hendrerit augue, ac tempor sem posuere at. Nulla facilisi. In et eleifend risus. Nullam commodo ante eget erat maximus, ac dapibus ex porttitor. Aliquam rutrum hendrerit gravida. Mauris vestibulum libero non gravida eleifend.

Nullam finibus quam sed sem pulvinar, et rutrum lorem scelerisque. Sed id auctor neque. Nulla lacinia eros sit amet diam tincidunt, at lacinia nulla mattis. Morbi malesuada elit in facilisis pretium. Phasellus sit amet pharetra augue, sit amet bibendum diam. Suspendisse a nulla sit amet tortor congue porttitor a ac metus. Fusce velit elit, cursus nec rhoncus eget, mollis sit amet ante. Integer quis est sem. Fusce rutrum orci urna.

Nullam ornare lectus in semper varius. Nunc vestibulum vulputate massa ut scelerisque. Fusce nec diam condimentum elit venenatis euismod id at orci. Proin quis ipsum accumsan, ultrices elit sed, mollis turpis. Aliquam sit amet velit sit amet est feugiat tristique eget quis libero. Etiam ut arcu quam. Nam nisi tellus, volutpat vel nunc eget, semper placerat purus. Nullam cursus lacus id massa luctus, sed finibus sem feugiat. Mauris bibendum vulputate molestie.

Morbi hendrerit ut massa ac tristique. Nulla facilisi. Sed rutrum interdum ultrices. Nulla facilisi. Donec id sapien convallis, congue ipsum id, sodales metus. Vivamus vitae nibh nec turpis pharetra dignissim. Aliquam et orci nec lectus pretium viverra. Vestibulum semper hendrerit pellentesque. Vivamus nec feugiat leo. Donec sit amet lorem et orci ornare facilisis.

Fusce enim lectus, sodales ut euismod ut, elementum a sem. Nunc maximus ligula ante, non mattis diam scelerisque a. In et molestie nisi, ac viverra purus. Praesent commodo sem sapien, ac posuere nunc molestie a. Nullam aliquam, lacus in rhoncus tristique, erat diam blandit ligula, sit amet facilisis orci erat sit amet turpis. Duis convallis varius pretium. In aliquet, arcu at vehicula eleifend, nisi nibh pretium libero, at tincidunt elit lacus ut augue. Cras bibendum tempus malesuada. Aliquam hendrerit libero vel neque pellentesque sollicitudin. Praesent cursus, massa sed egestas ultricies, leo dui viverra nisl, vel aliquet risus ante at sapien. Suspendisse erat diam, tincidunt vel commodo at, porttitor accumsan libero.

Suspendisse potenti. Nullam auctor eros sapien, at egestas nibh pretium et. Nulla a euismod libero. Cras consectetur, nibh vitae condimentum interdum, est nunc cursus lectus, non dapibus lorem velit vel metus. Sed eget ex posuere, euismod diam vel, porttitor magna. Proin sem erat, malesuada placerat orci id, vehicula mattis odio. Nulla tristique orci vitae velit accumsan, nec venenatis metus molestie. Pellentesque cursus ipsum erat, eu bibendum ligula venenatis id. Phasellus consequat odio metus, eu maximus nunc faucibus sit amet. In ultricies ligula eget sollicitudin finibus. Aliquam a dolor sit amet libero consequat commodo. Nunc nec velit porta, tincidunt ipsum id, fringilla ex. Donec euismod elementum sapien, in accumsan neque tristique porttitor. Morbi vel orci ut nisi condimentum condimentum sed a odio.

Sed bibendum, diam in porta viverra, mauris lorem luctus metus, sit amet hendrerit ante libero vitae felis. Donec mi orci, pretium vel rutrum ac, dignissim in ipsum. Aliquam erat volutpat. Ut ultrices felis dui, sed commodo ipsum lacinia fermentum. Aenean ac nisi eu felis imperdiet porta. Etiam euismod eros id dapibus ultricies. In vel sapien diam. In tincidunt orci blandit, varius mauris in, porta dui. Quisque imperdiet ex eu ante suscipit, scelerisque accumsan metus dictum. Etiam finibus, augue fermentum facilisis gravida, tellus risus maximus odio, ac interdum eros mi eu justo. Donec venenatis ac magna eu ornare. Integer scelerisque sapien eu lorem eleifend laoreet.

Morbi ullamcorper tortor eget sapien consequat, ut commodo risus dignissim. Nulla semper sagittis velit sed facilisis. Vivamus vehicula, massa sit amet maximus molestie, eros risus luctus metus, quis eleifend nulla neque rhoncus justo. Fusce egestas sem a tellus pulvinar interdum. Proin varius euismod est quis tincidunt. Sed eget sapien porttitor risus consectetur laoreet at et sem. Praesent mattis tortor quis urna gravida, a malesuada lectus ultrices.

Mauris id tempus odio. Curabitur et mauris sed mauris congue tempus. Ut blandit, urna non tincidunt venenatis, justo felis luctus risus, vitae volutpat sapien ex at libero. Maecenas lobortis ornare orci, sit amet vestibulum urna vestibulum non. Quisque scelerisque placerat dignissim. Aenean accumsan diam quis nibh ultricies pellentesque. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed molestie tempus sem, vel tincidunt tellus posuere vitae. In lacinia facilisis lacus, sed suscipit leo pharetra sed. Pellentesque fermentum ullamcorper sem. Suspendisse semper fringilla nunc. Pellentesque euismod tempus nunc vel venenatis. Vestibulum tellus dolor, gravida vitae mattis sed, cursus id quam. Mauris pulvinar a urna vitae sodales.

Curabitur at arcu iaculis, lacinia dui non, gravida ex. Sed imperdiet semper vulputate. Pellentesque mattis neque a sem interdum interdum. Donec molestie consectetur convallis. Ut ut orci ac leo condimentum maximus in a augue. Nam vel tellus vitae nisl hendrerit dignissim eget sit amet purus. Praesent congue quam nec sem auctor pellentesque. Cras velit dolor, rhoncus et elit in, varius sagittis risus.

Ut ullamcorper eget est a sagittis. Phasellus vitae elementum urna. Proin lobortis, lorem non commodo finibus, nisi nibh auctor eros, quis sodales mauris elit eget velit. Nam et enim sed elit tempus egestas id ac purus. Quisque sit amet placerat velit. Aliquam vitae fringilla purus, ullamcorper pharetra tortor. Phasellus egestas maximus faucibus. Morbi porta sagittis sem nec volutpat. Suspendisse id vulputate ex. Cras eu porttitor dui.

Nunc ac eros id libero auctor sollicitudin eget eu ipsum. Vivamus scelerisque diam id aliquam suscipit. Curabitur id varius libero, eu ultrices nisl. Sed pretium mi nec neque venenatis, tempus sodales neque blandit. Vestibulum fringilla nulla eu rhoncus fermentum. Curabitur sapien sem, efficitur sagittis consequat ac, pulvinar vitae libero. Nullam convallis feugiat ante, vel commodo felis pretium id.

Aliquam efficitur, lorem rutrum lacinia vestibulum, nulla sem auctor augue, nec dictum mauris libero sed urna. Donec et lectus odio. Quisque venenatis ut libero eget commodo. Nullam ultricies fermentum finibus. Nulla semper ipsum non dui bibendum, a condimentum quam mollis. Aenean viverra diam id elit pulvinar tristique. Vestibulum eleifend ut leo ac placerat.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed suscipit ornare arcu, sit amet ullamcorper libero accumsan eu. Nunc massa urna, ornare id purus nec, sodales vulputate dui. Vestibulum feugiat dignissim dui, at tincidunt lorem luctus non. Morbi venenatis mauris nisl, sed suscipit ligula varius eget. Vivamus at elit mauris. Aenean rutrum sem nec tincidunt iaculis. Fusce condimentum malesuada nunc vel convallis. Suspendisse potenti.

Curabitur rutrum risus in scelerisque luctus. Aliquam vel arcu porttitor ante sollicitudin fringilla vitae quis quam. Vestibulum scelerisque pulvinar purus, at venenatis ipsum iaculis in. Aenean vel mollis purus, vitae tristique nulla. Quisque hendrerit orci vel orci condimentum, eu lacinia nunc accumsan. Morbi in ultricies diam. Integer orci sapien, tristique in lacinia eget, finibus ut nibh. Donec sed malesuada erat. Donec ut odio eu felis sollicitudin vulputate posuere eget lacus. Vestibulum sit amet felis congue, aliquam felis ac, cursus nibh. Pellentesque blandit dapibus faucibus. Donec nisi enim, faucibus tristique viverra eget, ultricies blandit erat. Duis vitae purus a dolor porttitor lobortis quis ut eros. Fusce rhoncus et nulla et faucibus. Aliquam accumsan fringilla nisl, ac sollicitudin tortor mattis vel.

Aenean a feugiat magna. Etiam molestie sit amet turpis id dictum. Proin metus felis, pharetra vitae sapien nec, sollicitudin bibendum lacus. Ut et elementum dui. Ut vitae scelerisque ex, non tempor felis. Vivamus consectetur posuere vestibulum. Praesent vehicula id lectus eu tempor. Aliquam vehicula, arcu at vehicula hendrerit, lectus massa rutrum libero, quis facilisis purus urna et velit. Nulla facilisi.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rutrum massa nec tortor finibus lacinia. Integer lorem dolor, bibendum rutrum magna in, mollis pretium ante. Sed et lorem auctor, rutrum neque eget, semper eros. Aenean malesuada, odio id tempor condimentum, eros augue ultricies elit, ac feugiat ligula nisl auctor est. Integer aliquet tincidunt sem, eget sollicitudin felis molestie quis. Vivamus pretium turpis neque, at consectetur nibh efficitur in. Integer leo diam, vehicula quis mauris ut, fringilla egestas ante. Sed sodales ac orci sodales sollicitudin. Fusce sagittis cursus diam ut semper. Sed ultricies venenatis diam, at lacinia nulla sollicitudin id. In mattis diam justo, id efficitur leo semper non.

Quisque porta ac magna sed feugiat. Nulla a pulvinar lectus, nec facilisis arcu. Vestibulum ac ligula lectus. Curabitur ipsum velit, elementum et nunc bibendum, tincidunt congue lacus. Vestibulum malesuada erat justo, et tempus sem faucibus non. Praesent varius eros nec mauris auctor tristique. Nulla vel tincidunt nunc.

Suspendisse suscipit lacus odio, at tempus justo sollicitudin a. Aenean a viverra arcu. Nam elit lectus, ultrices sit amet purus a, scelerisque aliquam lacus. Nullam scelerisque dapibus pharetra. Phasellus tincidunt elit eu erat lobortis, nec consequat sem sollicitudin. Ut egestas auctor odio sed tempor. Suspendisse id lorem velit. Praesent et rhoncus leo. Sed a viverra sapien. Nulla facilisi. Suspendisse dictum velit diam. Nulla dapibus eleifend enim, cursus sagittis arcu sodales sed. Vestibulum sit amet imperdiet arcu.

Sed nisi orci, auctor ac tincidunt molestie, vulputate nec odio. Sed tempus dui</>
     )
}

export default Charts;